--SET search_path = public, pg_catalog;

SET statement_timeout = 0;
-- decommentare la riga seguente in caso di lancio da interprete di comando direttamente da linux
--SET client_encoding = 'LATIN1';
SET standard_conforming_strings = off;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET escape_string_warning = off;

-- inserimento associazione (utente,profilo)
Insert into W_ACCPRO (ID_ACCOUNT,COD_PROFILO) select 48,'VIGILANZA-CIG' from W_GENCHIAVI where TABELLA='W_GRUPPI' and not exists (select * from W_PROFILI where cod_profilo = 'VIGILANZA-CIG');
Insert into W_ACCPRO (ID_ACCOUNT,COD_PROFILO) select 49,'VIGILANZA-CIG' from W_GENCHIAVI where TABELLA='W_GRUPPI' and not exists (select * from W_PROFILI where cod_profilo = 'VIGILANZA-CIG');
Insert into W_ACCPRO (ID_ACCOUNT,COD_PROFILO) select 50,'VIGILANZA-CIG' from W_GENCHIAVI where TABELLA='W_GRUPPI' and not exists (select * from W_PROFILI where cod_profilo = 'VIGILANZA-CIG');
-- inserimento eventuale gruppo
Update W_GENCHIAVI Set CHIAVE=CHIAVE+1 where TABELLA='W_GRUPPI' and not exists (select 1 from W_GRUPPI where cod_profilo='VIGILANZA-CIG');
Insert into W_GRUPPI (ID_GRUPPO,NOME,DESCR,COD_PROFILO) Select (select CHIAVE from W_GENCHIAVI where TABELLA='W_GRUPPI'),'Vigilanza - Richiesta CIG','default per il profilo VIGILANZA-CIG','VIGILANZA-CIG' from W_GENCHIAVI where tabella='W_GRUPPI' and not exists (select * from W_GRUPPI where cod_profilo='VIGILANZA-CIG');
-- inserimento associazione (utente,gruppo)
Insert into W_ACCGRP (ID_ACCOUNT,ID_GRUPPO,PRIORITA) select 48,ID_GRUPPO,0 from W_GRUPPI where COD_PROFILO='VIGILANZA-CIG'  and not exists (select * from W_ACCGRP A inner join W_GRUPPI G on A.id_gruppo=G.id_gruppo where G.cod_profilo='VIGILANZA-CIG' and A.id_account=48);
Insert into W_ACCGRP (ID_ACCOUNT,ID_GRUPPO,PRIORITA) select 49,ID_GRUPPO,0 from W_GRUPPI where COD_PROFILO='VIGILANZA-CIG'  and not exists (select * from W_ACCGRP A inner join W_GRUPPI G on A.id_gruppo=G.id_gruppo where G.cod_profilo='VIGILANZA-CIG' and A.id_account=49);
Insert into W_ACCGRP (ID_ACCOUNT,ID_GRUPPO,PRIORITA) select 50,ID_GRUPPO,0 from W_GRUPPI where COD_PROFILO='VIGILANZA-CIG'  and not exists (select * from W_ACCGRP A inner join W_GRUPPI G on A.id_gruppo=G.id_gruppo where G.cod_profilo='VIGILANZA-CIG' and A.id_account=50);

-- pulizia profilo eseguita sempre
Delete from W_PROAZI where COD_PROFILO='VIGILANZA-CIG';
Delete from W_PROFILI where COD_PROFILO='VIGILANZA-CIG';

-- inserimento (o reinserimento) testata e configurazione profilo
INSERT INTO W_PROFILI (COD_PROFILO,CODAPP,NOME,DESCRIZIONE,FLAG_INTERNO,DISCRIMINANTE,COD_CLIENTE,CRC) VALUES ('VIGILANZA-CIG','PG','Richiesta CIG','Richiesta e gestione del codice identificativo della gara',1,null,0,2909853131);

INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','GENE.G_NOTEAVVISI.*',1,3472779466);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','GENE.TECNI.CFTEC',1,3479026769);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','GENE.TECNI.COGTEI',1,2499727429);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','GENE.TECNI.INCTEC',1,4106031844);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','GENE.TECNI.NOMETEI',1,3837335197);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','GENE.TECNI.NOMTEC',1,1165377966);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','GENE.UFFINT.*',1,155810349);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','W3.*',1,449480453);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','W3.GRP.*',1,2466536918);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','W3.GRPUSRSYS.*',1,3563165065);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','W3.PERM.*',1,2906219683);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','W3.UNIT.*',1,2951152961);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','W3.UNITGRP.*',1,2762309590);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','W3.UNITUSRSYS.*',1,903529818);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','W3.W3AZIENDAUFFICIO.*',1,2721701375);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','W3.W3GARA.*',1,1000089330);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','W3.W3GARADOC.*',1,1183529266);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','MOD','W3.W3GARAREQ.*',1,1278869908);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','W3.W3GARAREQ.*',1,597974785);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','MOD','W3.W3GARAREQCIG.*',1,4068894752);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','W3.W3GARAREQCIG.*',1,986832077);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','MAN','W3.W3GARAREQCIG.CIG',1,1872363939);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','MOD','W3.W3GARAREQDOC.*',1,4020320879);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','W3.W3GARAREQDOC.*',1,670469762);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','W3.W3LOTT.*',1,3944104309);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','W3.W3LOTTCATE.*',1,1586610964);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','W3.W3LOTTCUP.*',1,4040811603);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','W3.W3LOTTTIPI.*',1,2951608897);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','W3.W3USRSYS.*',1,870460166);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','COLS','VIS','W3.W3USRSYSCOLL.*',1,2366705270);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','FUNZ','VIS','ALT.GENE.C0OGGASS',0,1888279893);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','FUNZ','VIS','ALT.GENE.G_NOTEAVVISI',0,4289628934);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','FUNZ','VIS','ALT.GENE.HELPPAGINA',0,2611775279);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','FUNZ','VIS','ALT.GENE.Homepage-EseguiReport',0,3712486845);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','FUNZ','VIS','ALT.GENE.W_MODELLI',0,2702599471);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','FUNZ','VIS','DEL.W3.W3USRSYS-Scheda.DEL-W3AZIENDAUFFICIO',0,2183655613);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','FUNZ','VIS','INS.W3.W3AZIENDAUFFICIO-lista-popup.nuovo',0,1528018326);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','FUNZ','VIS','INS.W3.W3USRSYS-Scheda.INS-W3AZIENDAUFFICIO',0,389692718);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','FUNZ','VIS','INS.W3.W3USRSYS-Scheda.SCHEDANUOVO',0,1827014000);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','FUNZ','VIS','MOD.W3.W3AZIENDAUFFICIO-scheda-popup.SCHEDAMOD',0,3407415070);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','MASC','VIS','GARE.V_GARE_TORN-lista',0,3390890272);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','MENU','VIS','ARCHIVI',1,814646743);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','MENU','VIS','BANDI',0,2408058414);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','MENU','VIS','GARE',0,266636407);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','MENU','VIS','SCHEDE',0,3381649588);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','MENU','VIS','SIMOG-CIG',1,2686457625);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','SEZ','VIS','GENE.SchedaTecni.ALT',0,835318545);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','SUBMENU','VIS','ARCHIVI.Archivio-amministrazioni',0,1486901188);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','SUBMENU','VIS','ARCHIVI.Archivio-imprese',0,4225977924);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','SUBMENU','VIS','ARCHIVI.Archivio-stazioni-appaltanti',0,1361484355);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','SUBMENU','VIS','ARCHIVI.Archivio-tecnici-imprese',0,1121532323);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','SUBMENU','VIS','ARCHIVI.Archivio-utenti',0,3100152466);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','SUBMENU','VIS','UTILITA.Gestione-gruppi-utenti',0,3095641232);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','SUBMENU','VIS','UTILITA.Import-export-modelli',0,3037951636);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','SUBMENU','VIS','UTILITA.Import-export-report',0,2149004479);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','TABS','VIS','GENE.G_NOTEAVVISI',1,3260942466);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','TABS','VIS','GENE.TECNI',1,1374747680);
INSERT INTO W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('VIGILANZA-CIG','TABS','VIS','W3.*',1,787847363);
